name: Jira Integration
on:
  issues:
    types: [opened, labeled]

jobs:
  create_jira_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create Jira issue
        uses: atlassian/gajira-create@v3
        with:
          project: GDT        # your Jira project key
          issuetype: Task     # or Bug/Story etc.
          summary: "${{ github.event.issue.title }}"
          description: "This task was automatically created from an issue in GitHub ${{ github.event.issue.html_url }} ${{ github.event.issue.body }}"
          fields: '{
            "labels": ["rgemini-github-import"], # this should be specific to the repo
            "parent": { "key": "GDT-160" }, # link to Rgemini Epic (this should be specific to the repo)
            "assignee": { "id": "1d1f41de-6740-4eb3-b6f9-8289c07396eb" } # automatically assign to specific user (repo-specific)
          }'
