name: Create Jira issue on GitHub issue
on:
  issues:
    types: [opened]

jobs:
  createJiraIssue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Jira issue
        uses: atlassian/gajira-create@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_PASS }}
        with:
          project: GDT   # Jira project key
          issuetype: Task
          summary: "${{ github.event.issue.title }}"
          description: "${{ github.event.issue.body }}"